name: Validate Schemas

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: "3.0"
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Validate Schemas
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install json_schemer
        json_schemer schemas/cities.schema.json cities.json
        json_schemer schemas/places.schema.json cities/rastede/places.json
